Fix minibuffer completion style bug.
seagle0128/.emacs.d pull request #355
Opened 2022-04-29 10:28 UTC by 7ym0n

see #354

2022-04-30 15:39 UTC, seagle0128 requested changes

2022-04-30 15:39 UTC, seagle0128 commented on lisp/init-dict.el
> -                           :internal-border-color (face-background 'posframe-border nil t)
Why change the faces?

2022-04-30 15:39 UTC, seagle0128 commented on lisp/init-lsp.el
> -                   lsp-ui-doc-border (face-background 'posframe-border nil t)
Same as above.

2022-04-30 15:58 UTC, closed without merging

2022-04-30 15:58 UTC, seagle0128 commented
It was fixed in cab662ce8d0a0dfb10d383f55824a3f3d83fa448.

2022-05-03 12:51 UTC, 7ym0n commented
set completion style for `minibuffer'.

childframe-workable-p is false, it's not work.